/**
 * Service worker registration — 07_PWA_OFFLINE.md §3, §4
 *
 * Written against the platform API rather than `virtual:pwa-register`, for two
 * reasons. The plugin's helper pulls `workbox-window` into the application
 * bundle, which M8 left with little room; and the update lifecycle we want is
 * *narrower* than the helper's, so most of what it offers would be unused
 * code implementing behaviour we have specifically ruled out.
 *
 * The service worker itself is still generated by Workbox. Precaching and
 * fetch handling are the parts where a hand-rolled bug persists across
 * reloads, and that is exactly where the tool earns its place.
 *
 * **The one rule this file exists to enforce: nothing reloads the page except
 * the user.** A new version waits. It is announced. It activates when someone
 * asks for it and not before.
 */

/** How often to ask the server whether there is a new version. */
const UPDATE_INTERVAL_MS = 60 * 60 * 1000;

export type PwaEvent =
  /** A new version is installed and waiting. */
  | { readonly kind: 'update-available' }
  /** Everything is cached; the app will work offline from now on. */
  | { readonly kind: 'offline-ready' }
  /** Registration failed. The app still works; it just will not work offline. */
  | { readonly kind: 'unavailable'; readonly reason: string };

export interface ServiceWorkerHandle {
  /** Activates the waiting worker and reloads. Only ever from a user action. */
  applyUpdate: () => void;
  /** Stops the periodic checks and listeners. */
  dispose: () => void;
}

const NOOP: ServiceWorkerHandle = {
  applyUpdate: () => undefined,
  dispose: () => undefined,
};

/**
 * Registers the service worker, if this browser and build have one.
 *
 * Returns a handle rather than throwing or logging: whether the app can work
 * offline is product state, and the caller decides what to say about it.
 */
export function registerServiceWorker(notify: (event: PwaEvent) => void): ServiceWorkerHandle {
  // `import.meta.env.PROD` is replaced at build time, so the whole body is
  // dropped from a development bundle. A stale service worker during
  // development is a debugging trap with nothing to gain.
  if (!import.meta.env.PROD) return NOOP;
  if (typeof navigator === 'undefined' || !('serviceWorker' in navigator)) {
    notify({ kind: 'unavailable', reason: 'This browser does not support service workers.' });
    return NOOP;
  }

  let registration: ServiceWorkerRegistration | null = null;
  let timer: ReturnType<typeof setInterval> | null = null;
  let reloading = false;

  /**
   * A worker in `installed` state is only an *update* if something is already
   * controlling the page. On a first-ever visit the same state means the app
   * has just become offline-capable, which is a different message entirely.
   */
  const onInstalled = (worker: ServiceWorker): void => {
    if (navigator.serviceWorker.controller === null) notify({ kind: 'offline-ready' });
    else if (worker.state === 'installed') notify({ kind: 'update-available' });
  };

  const watch = (worker: ServiceWorker | null): void => {
    if (worker === null) return;
    if (worker.state === 'installed') {
      onInstalled(worker);
      return;
    }
    worker.addEventListener('statechange', () => {
      if (worker.state === 'installed') onInstalled(worker);
    });
  };

  // A reload is triggered by us, once, after the user consents. Guarding it
  // matters: without the flag a browser that fires `controllerchange` more
  // than once puts the page into a reload loop.
  const onControllerChange = (): void => {
    if (!reloading) return;
    reloading = false;
    window.location.reload();
  };
  navigator.serviceWorker.addEventListener('controllerchange', onControllerChange);

  void navigator.serviceWorker
    .register('/sw.js', { scope: '/' })
    .then((created) => {
      registration = created;

      // Already waiting when the page loaded — a previous visit installed it
      // and the user never applied it.
      if (created.waiting !== null && navigator.serviceWorker.controller !== null) {
        notify({ kind: 'update-available' });
      }
      watch(created.installing);
      created.addEventListener('updatefound', () => {
        watch(created.installing);
      });

      // Fails harmlessly offline, which is the expected case rather than an
      // error: update checking is explicitly outside the offline guarantee
      // (07_PWA_OFFLINE.md §1.1), so nothing is reported when it fails.
      timer = setInterval(() => {
        void created.update().catch(() => undefined);
      }, UPDATE_INTERVAL_MS);
    })
    .catch((error: unknown) => {
      // Private mode, an enterprise policy, or an unsupported context. The
      // application works; it simply will not work offline.
      notify({
        kind: 'unavailable',
        reason: error instanceof Error ? error.message : 'Registration failed.',
      });
    });

  return {
    applyUpdate: () => {
      const waiting = registration?.waiting ?? null;
      if (waiting === null) {
        // Nothing to activate. Reloading anyway would be a pointless
        // interruption, so this does nothing.
        return;
      }
      reloading = true;
      waiting.postMessage({ type: 'SKIP_WAITING' });
    },
    dispose: () => {
      if (timer !== null) clearInterval(timer);
      timer = null;
      navigator.serviceWorker.removeEventListener('controllerchange', onControllerChange);
    },
  };
}
