import { useRef, useState } from 'react';

import { exportAll, importAll } from '@/application/history/historyStore';
import type { ImportReport } from '@/domain/history/entry';
import { MAX_IMPORT_BYTES, parseImportText } from '@/domain/history/transfer';

import styles from './history.module.css';

/**
 * Export and import — 06_DATA_STORAGE.md §8
 *
 * Export exists because browser storage can vanish without the user doing
 * anything wrong: clearing site data, a storage-pressure eviction, a new
 * profile. A file is the only durable backup a client-only app can offer.
 *
 * **An import file is hostile input.** It came from a filesystem, so it may
 * have been edited or generated by something else entirely. Nothing here
 * trusts it: the text is size-checked before parsing, parsed with a reviver
 * that drops `__proto__`, and every record then goes through the same
 * validation a database record does.
 */

export function HistoryTransfer(): React.JSX.Element {
  const fileInput = useRef<HTMLInputElement>(null);
  const [message, setMessage] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);

  const download = async (): Promise<void> => {
    const envelope = await exportAll();
    if (envelope === null) {
      setMessage('History could not be read for export.');
      return;
    }

    const blob = new Blob([JSON.stringify(envelope, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `syntaxlab-history-${new Date().toISOString().slice(0, 10)}.json`;
    link.click();
    // Revoked immediately: the click has already handed the blob to the
    // browser's download machinery, and holding the URL pins the data in memory.
    URL.revokeObjectURL(url);

    setMessage(
      `Exported ${envelope.entryCount.toLocaleString('en')} ${envelope.entryCount === 1 ? 'entry' : 'entries'}.`,
    );
  };

  const upload = async (file: File): Promise<void> => {
    setBusy(true);
    try {
      if (file.size > MAX_IMPORT_BYTES) {
        setMessage(`That file is too large to import (limit ${MAX_IMPORT_BYTES / 1_000_000} MB).`);
        return;
      }

      const parsed = parseImportText(await file.text());
      if (!parsed.ok) {
        setMessage(parsed.error);
        return;
      }

      const report = await importAll(parsed.value, 'merge');
      setMessage(report === null ? 'That file could not be imported.' : describe(report));
    } catch {
      // A file that cannot even be read — removed mid-pick, or a permission
      // revoked. Reported rather than left as a silent no-op.
      setMessage('That file could not be read.');
    } finally {
      setBusy(false);
    }
  };

  return (
    <div className={styles.transfer}>
      <button
        type="button"
        className={styles.linkAction}
        disabled={busy}
        onClick={() => {
          void download();
        }}
      >
        Export
      </button>

      <button
        type="button"
        className={styles.linkAction}
        disabled={busy}
        onClick={() => {
          fileInput.current?.click();
        }}
      >
        Import
      </button>

      <input
        ref={fileInput}
        type="file"
        accept="application/json,.json"
        className="srOnly"
        // Not labelled as a control: the visible button above is the control,
        // and this input exists only because file pickers cannot be opened
        // any other way.
        tabIndex={-1}
        aria-hidden="true"
        onChange={(event) => {
          const file = event.target.files?.[0];
          // Cleared so picking the same file twice fires a change both times.
          event.target.value = '';
          if (file !== undefined) void upload(file);
        }}
      />

      {message !== null ? (
        <p className={styles.transferMessage} role="status">
          {message}
        </p>
      ) : null}
    </div>
  );
}

function describe(report: ImportReport): string {
  const parts: string[] = [];
  if (report.imported > 0) parts.push(`${report.imported} added`);
  if (report.updated > 0) parts.push(`${report.updated} updated`);
  if (report.skipped > 0) parts.push(`${report.skipped} skipped`);
  if (parts.length === 0) return 'Nothing new to import — every entry was already here.';

  const summary = `Imported: ${parts.join(', ')}.`;
  // The reasons matter: "12 skipped" with no explanation reads as data loss.
  return report.reasons.length === 0 ? summary : `${summary} Skipped because: ${report.reasons.join('; ')}.`;
}
