import {
  EXPORT_FORMAT,
  EXPORT_FORMAT_VERSION,
  type ExportEnvelope,
  type HistoryEntry,
} from './entry';
import { readEntry } from './validate';

/**
 * Export and import — 06_DATA_STORAGE.md §8, 05_SECURITY.md §10.2
 *
 * Export exists for a reason beyond convenience: browser storage can vanish
 * without the user doing anything wrong (§9.1), and a file is the only durable
 * backup path a client-only application can offer.
 *
 * **An import file is hostile input.** It arrives from a filesystem, so it may
 * have been edited, generated by another tool, or crafted. Every record goes
 * through the same `readEntry` reconstruction that a database record does, so
 * there is exactly one validation path rather than two that can drift.
 */

/** Refuses a file large enough to be a denial of service rather than a backup. */
export const MAX_IMPORT_BYTES = 20_000_000;
export const MAX_IMPORT_ENTRIES = 10_000;

export interface ImportResult {
  readonly entries: readonly HistoryEntry[];
  readonly skipped: number;
  readonly reasons: readonly string[];
}

export function buildEnvelope(
  entries: readonly HistoryEntry[],
  appVersion: string,
): ExportEnvelope {
  return {
    format: EXPORT_FORMAT,
    formatVersion: EXPORT_FORMAT_VERSION,
    generatedAt: new Date().toISOString(),
    appVersion,
    entryCount: entries.length,
    entries,
  };
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

/** Checks the envelope itself, before any record is looked at. */
function checkEnvelope(value: unknown): readonly unknown[] | string {
  if (!isRecord(value)) return 'That file does not contain a JSON object.';

  if (value.format !== EXPORT_FORMAT) {
    return 'That is not a SyntaxLab export. The file must have a `format` of "syntaxlab-export".';
  }

  const formatVersion = value.formatVersion;
  if (typeof formatVersion !== 'number' || !Number.isInteger(formatVersion)) {
    return 'The export has no usable format version.';
  }
  if (formatVersion > EXPORT_FORMAT_VERSION) {
    return `That export was written by a newer version of SyntaxLab (format ${formatVersion}). Update before importing it.`;
  }

  if (!Array.isArray(value.entries)) return 'The export contains no entries array.';
  if (value.entries.length > MAX_IMPORT_ENTRIES) {
    return `That export holds ${value.entries.length.toLocaleString('en')} entries; the limit is ${MAX_IMPORT_ENTRIES.toLocaleString('en')}.`;
  }

  return value.entries as readonly unknown[];
}

/**
 * Turns a parsed file into entries, or explains why it is not one.
 *
 * Returns a string on outright rejection — the file is not ours, or is
 * unusable as a whole. Individual bad records are skipped and counted instead,
 * because one corrupt entry in a 500-entry backup should not cost the user the
 * other 499.
 */
export function readEnvelope(value: unknown): ImportResult | string {
  const records = checkEnvelope(value);
  if (typeof records === 'string') return records;

  const entries: HistoryEntry[] = [];
  const reasons: string[] = [];
  let skipped = 0;

  for (const record of records) {
    const outcome = readEntry(record);
    if (outcome.kind === 'ok') {
      entries.push(outcome.entry);
      continue;
    }
    skipped += 1;
    // Bounded: a file of ten thousand bad records must not produce ten
    // thousand lines of explanation.
    const reason = outcome.kind === 'future' ? 'created by a newer version' : outcome.reason;
    if (reasons.length < 5 && !reasons.includes(reason)) reasons.push(reason);
  }

  return { entries, skipped, reasons };
}

/**
 * Parses import text safely.
 *
 * `JSON.parse` is used here rather than our own parser because this is our own
 * format rather than a document being explained, and the reviver is what makes
 * it safe: `__proto__` is dropped before the object ever exists, so a crafted
 * file cannot reach `Object.prototype` (05_SECURITY.md §7).
 */
export type ParsedImport =
  { readonly ok: true; readonly value: unknown } | { readonly ok: false; readonly error: string };

export function parseImportText(text: string): ParsedImport {
  if (text.length > MAX_IMPORT_BYTES) {
    return {
      ok: false,
      error: `That file is ${(text.length / 1_000_000).toFixed(1)} MB; the limit is ${MAX_IMPORT_BYTES / 1_000_000} MB.`,
    };
  }
  try {
    const value: unknown = JSON.parse(text, (key, parsed: unknown) =>
      key === '__proto__' ? undefined : parsed,
    );
    return { ok: true, value };
  } catch {
    return { ok: false, error: 'That file is not valid JSON.' };
  }
}
